
# server

server:
  address:
  port: 8080

upload:
  savepath: "g:/img/picture"

redis_server:
  address: "choucaicai.top:6378"
  password: ""
  database: 0

mysql_server:
  address: "root:0026@tcp(choucaicai.top:3308)/mall"
  password: ""
  database: 0

newarrary:
  - name: "lll"
    age: "12"
  - name: 'hhh'
    age: '13'

