
# server

server:
  address:
  port: 8000

upload:
  savepath: "g:/img/picture"

redis_server:
  address: "localhost:6379"
  password: ""
  database: 0

mysql_server:
  address: "root:@tcp(localhost:3306)/mall"
  password: ""
  database: 0

newarrary:
  - name: "lll"
    age: "12"
  - name: 'hhh'
    age: '13'

