
# server

server:
  address:
  port: 8080

upload:
  savepath: "g:/img/picture"

redis_server:
  address: "127.0.0.1:6378"
  password: ""
  database: 0

mysql_server:
  address: "root:0026@tcp(127.0.0.1:3308)/mall"
  password: ""
  database: 0
